#! /bin/bash --login

#PBS -N vac_HydA2HSD
#PBS -q Std
#PBS -l nodes=2:ppn=2
#PBS -m abe
#PBS -M user.name@domain.name
#PBS -o pbs.charmm.out
#PBS -e pbs.charmm.err

#Because charmm uses shared libraries, add charmm to your default
#module list before running by typing the following:

#module initadd charmm/31b1

cd $PBS_O_WORKDIR

#simple serial charmm job
#charmm < GB.inp > GBminimization.out.$PBS_JOBID

# example: run an MPI job
cat > stream.inp << EOF
* Internal energy calculation last 2000 snapshots of production dynamics
*
stream @stream
stop
EOF

export input="stream=DYN_ENERGY.INP"

which charmm.mpi.xxlarge
mpicmd charmm.mpi.xxlarge $input < stream.inp > internal_energy.out

